const colors = {
  SCREEN_BACKGROUND: '#FFFFFF',
  SCREEN_TITLE_TEXT: '#000000',
  SELECTED_COUNTRY_BUTTON: '#889FBB',
  SELECTED_COUNTRY_BUTTON_TEXT: '#FFFFFF',
  COUNTRY_BUTTON: '#FFFFFF',
  COUNTRY_BUTTON_TEXT: '#A5A5A5',
  PUBLISHER_TEXT: '#BFBABA',
  LIST_ARTICLE_TITLE_TEXT: '#BFBABA',
  LIST_ARTICLE_POSTDATE_TEXT: '#777777',
  LIST_ARTICLE_BODY_TEXT: '#000000',
  ARTICLE_BORDER: '#F0F0F0',
  ARTICLE_TITLE_TEXT: '#000000',
  ARTICLE_BODY_TEXT: '#777777',
  ARTICLE_AUTHOR: '#000000',
  ARTICLE_POSTDATE: '#000000',
  LOADER: '#9CA3AF',
  ARTICLE_URL: '#1A30FF',
};

export default colors;
